version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: alice.Dockerfile
      args:
        BUILD_VERSION: 6.1.0.order_gobgp_routes
        ARCHIVE_URL: https://github.com/wrgeorge1983/alice-lg/archive

    environment:
      DANGEROUSLY_DISABLE_HOST_CHECK: "true"
    ports:
      - "80:80"
    networks:
      - gobgpNetwork
    # volumes:
    #  - ./etc/alice-lg:/etc/alice-lg

  bgp:
    # image: jauderho/gobgp:latest
    build:
      context: .
      dockerfile: gobgp.Dockerfile
      args:
        BUILD_VERSION: v3.26.0
        ARCHIVE_URL: https://github.com/osrg/gobgp/archive

    ports:
      - "179:179"
      - "50051:50051"
    # volumes:
    #   - ./gobgpd.yml:/config/input_gobgpd.yml
    # command: ["gobgpd", "-t", "yaml", "-f", "/etc/gobgpd/gobgpd.yml"]
    command: [ "gobgpEntrypoint" ]
    environment:
      INPUT_CONFIG_FILE: /config/gobgpd_empty.yml
      OUTPUT_CONFIG_FILE: /config/gobgpd.yml
      GOBGPD_PATH: gobgpd
      LOCAL_AS: 65006
      ROUTER_ID: 172.16.32.69
      PEER1_ADDRESS: 192.168.100.6
      PEER1_AS: 65006
    networks:
      - gobgpNetwork

networks:

  gobgpNetwork:
    name: "gobgpNetwork"
    ipam:
      driver: default
      config:
        - subnet: 192.168.59.0/24
